# Generated by Django 5.0.6 on 2024-05-26 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('specialRules', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sagaDice', models.PositiveIntegerField(default=1)),
                ('unitType', models.CharField(choices=[('Warlord', 'Warlord'), ('Hearthguard', 'Hearthguard'), ('Warrior', 'Warrior'), ('Levy', 'Levy')], default='Hearthguard', max_length=20)),
                ('unitName', models.CharField(default='Hearthguard', max_length=50)),
                ('equipment', models.CharField(choices=[('Bows', 'Bows'), ('Bows and Slings', 'Bows and Slings'), ('Composite Bows', 'Composite Bows'), ('Crossbows', 'Crossbows'), ('Heavy Weapons', 'Heavy Weapons'), ('Improvised Projectiles', 'Improvised Projectiles'), ('Javelins', 'Javelins'), ('Sarissa', 'Sarissa'), ('Slings', 'Slings'), ('Unarmed', 'Unarmed'), ('Horse', 'Horse'), ('Horse, Cataphract', 'Horse, Cataphract'), ('Horse, Composite Bows', 'Horse, Composite Bows'), ('Horse, Javelin', 'Horse, Javelin'), ('Camel, Composite Bows', 'Camel, Composite Bows'), ('Camel, Javelin', 'Camel, Javelin'), ('-', '-')], default='-', max_length=50)),
                ('armourMelee', models.PositiveIntegerField(default=5)),
                ('armourRanged', models.PositiveIntegerField(default=5)),
                ('aggMelee', models.FloatField(default=2)),
                ('aggRanged', models.FloatField(default=0)),
                ('specialRules', models.TextField(default='-')),
                ('isLegendary', models.BooleanField(default=False)),
                ('factionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saga.faction')),
            ],
        ),
    ]
