# Generated by Django 5.0.6 on 2024-05-25 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitType', models.CharField(default='Hero', max_length=20)),
                ('unitName', models.CharField(default='Warlord', max_length=50)),
                ('equipment', models.CharField(default='-', max_length=20)),
                ('armourMelee', models.PositiveIntegerField(default=5)),
                ('armourRanged', models.PositiveIntegerField(default=5)),
                ('aggMelee', models.FloatField(default=8)),
                ('aggRanged', models.FloatField(default=0)),
                ('specialRules', models.TextField(default='Warlord')),
                ('factionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saga.faction')),
            ],
        ),
    ]
