# Generated by Django 5.0.6 on 2024-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unitType',
            field=models.CharField(choices=[('Warlord', 'Warlord'), ('Hearthguard', 'Hearthguard'), ('Warrior', 'Warrior'), ('Levy', 'Levy')], default='Hero', max_length=20),
        ),
    ]
