# Generated by Django 5.0.6 on 2024-05-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0002_alter_unit_unittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='sagaDice',
            field=models.IntegerField(default=1),
        ),
    ]
