# Generated by Django 5.0.6 on 2024-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0003_unit_sagadice'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='isLegendary',
            field=models.BooleanField(default=False),
        ),
    ]
