# Generated by Django 5.0.6 on 2024-05-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0004_unit_islegendary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='sagaDice',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
