# Generated by Django 5.0.6 on 2024-05-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0004_alter_faction_id_alter_faction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='factionName',
            new_name='factionId',
        ),
    ]
