# Generated by Django 5.0.6 on 2024-05-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0005_rename_factionname_unit_factionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='numModels',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
