# Generated by Django 5.0.6 on 2024-05-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0007_alter_unit_aggmelee_alter_unit_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='faction',
            name='specialRules',
            field=models.TextField(default=''),
        ),
    ]
