# Generated by Django 5.0.6 on 2024-05-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0008_faction_description_faction_specialrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faction',
            name='specialRules',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='equipment',
            field=models.CharField(choices=[('Bows', 'Bows'), ('Bows and Slings', 'Bows and Slings'), ('Composite Bows', 'Composite Bows'), ('Crossbows', 'Crossbows'), ('Heavy Weapons', 'Heavy Weapons'), ('Improvised Projectiles', 'Improvised Projectiles'), ('Javelins', 'Javelins'), ('Sarissa', 'Sarissa'), ('Slings', 'Slings'), ('Unarmed', 'Unarmed'), ('Horse', 'Horse'), ('Horse, Cataphract', 'Horse, Cataphract'), ('Horse, Composite Bows', 'Horse, Composite Bows'), ('Horse, Javelin', 'Horse, Javelin'), ('Camel, Composite Bows', 'Camel, Composite Bows'), ('Camel, Javelin', 'Camel, Javelin'), ('-', '-')], default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='specialRules',
            field=models.TextField(default='-'),
        ),
    ]
